repos:
      - repo: https://github.com/vamshireddyk887/VPC_Using_Terraform.git
        rev: main
        hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: terraform
            name: terraform
            entry: terraform
            language: system  
            files: \.tf$  
            types: [exec]  
            args: 
              - fmt 
              - validate 
